name: CI to Docker Hub

#describe what will effect workflow trigger
on:
  #@time(push) to Github Repository, main branch
  push:
    branches: [ main ]

#describe the set of jobs to be performed in the workflow
jobs:
  #Job 1
  build:
    #which image should be used to generate the container in which "build" job will run?
    runs-on: ubuntu-latest
    steps:
      #step 1//5: check out repository under $GITHUB_WORKSPACE
      - name: Check out Repo
        uses: actions/checkout@v2
      #step 2//5: use PAT + username to login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME     }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #step 3//5: use BuildKit under the hood via a Buildx action. This requries add'l setup
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1
      #step 4//5
      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      #step 5//5
      - name: Image digest
        uses: echo ${{ steps.docker_build.outputs.digest }}
