name: Store in GitHub registry


#describe what will effect workflow trigger
on:
  # push if the commit is a production version version 
  push:
    branches: [ master ]
  # schedule a nightly build @time(1:30, UTC)
  schedule:
    # '*' is a special character in YAML. Therefore, the string below must be quoted to escape.
    - cron: '30 1 * * *'

#describe the set of jobs to be performed in the workflow
jobs:
  #Job 1
  build:
    #which image should be used to generate the container in which "build" job will run?
    runs-on: ubuntu-latest
    steps:

      # new step (step 0//5): add builder and build cache snippets
      # this will reduce the build time by caching images (download once, use N)
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      #step 1//5: check out repository under $GITHUB_WORKSPACE
      - name: Check out Repo
        uses: actions/checkout@v2

      #step 3//5: use BuildKit under the hood via a Buildx action. This requries add'l setup
      - name: Set up Docker Buildx
        id:   buildx
        uses: docker/setup-buildx-action@v1

      #step 2//5
      #delta_ change Docker Hub login info to that of GitHub Container Registry
      - name: Login to GH Container Registry
      # - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_TOKEN }}
            #username: ${{ github.actor         }}
      #     username: ${{ secrets.DOCKER_HUB_USERNAME     }}
      #password: ${{ secrets.GITHUB_TOKEN }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}



      #step 4//5
      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          #delta_ incorporate a build cache
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/simplewhale:latest
          #delta_ use the cache from step 0//5 as a store and retrieval point
          cache-from: type=local,src=/tmp/.buildx-cache
          #delta_ use the cache from step 0//5 as a store and retrieval point
          cache-to: type=local,dest=/tmp/.buildx-cache

      #step 5//5
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

